Create new update properties function
PostHog/plugin-server pull request #611
Opened 2021-10-26 05:24 UTC by tiina303

## Changes

Add function to update user properties predictably, when ingestion can occur in any order.

Next up:
1. gating to be able to roll this out for our team only first

## Checklist

-   [ ] Updated Settings section in README.md, if settings are affected
-   [ ] Jest tests

2021-10-26 11:21 UTC, yakkomajuri requested changes
looking good, a few nits.

also, let's have the tests in this PR?

2021-10-26 11:21 UTC, yakkomajuri commented on src/utils/db/db.ts
> +    private addPropsUpdateValues(
let's extract this to utils

2021-10-26 11:21 UTC, yakkomajuri commented on src/utils/db/db.ts
> +        const propertyUpdateExpressionsArr: any[] = []
I guess this can be called a nit but I'm much more in favor of returning this than modifying in place. Makes things cleaner in my opinion. Leveraging calling by sharing with simpler objects like arrays can just get confusing IMO

2021-10-26 11:21 UTC, yakkomajuri commented on src/utils/db/db.ts
> +                // can I throw in a transaction
sure, yeah. take a look at how the `postgresTransaction` method handles this. IIRC it will catch, log to Sentry, and ROLLBACK.

2021-10-26 11:21 UTC, yakkomajuri commented on src/utils/db/db.ts
> +        if (this.kafkaProducer && personFound) {
This is a comment for us, not you specifically, as I contributed to this implementation.

But, effectively, for every event with `$set`, we'll add a new row to CH (which will hopefully be collapsed, but still). Could be worth doing some checking on if we actually updated something before producing to Kafka.

Given you now fetch the person before updating props, should be fine to just check the returned props against the persons props and deciding to issue a CH insert or not

2021-10-26 11:21 UTC, yakkomajuri commented on src/utils/db/db.ts
> +                props, // todo: right type
what do you mean with right type?

2021-10-26 11:21 UTC, yakkomajuri commented on src/utils/db/db.ts
> +                personFound.is_identified, // is this safe to use this way
yup

2021-10-26 11:21 UTC, yakkomajuri commented on src/utils/db/db.ts
> +                teamId,
this is ultimately the same thing, but for clarity, let's do `personFound.team_id`. Just so the reader doesn't need to consider where else this ID might be coming from

2021-10-28 09:27 UTC, yakkomajuri requested changes
some more tests needed but we're moving forward

2021-10-28 09:27 UTC, yakkomajuri commented on src/utils/db/db.ts
> +        if (this.kafkaProducer && personFound && personFound.properties != props) {
JS is nice but not _that_ nice. This object comparison will always return false.

We probably already have a lib or util somewhere in this codebase to compare objects so let's use that.

Some reading:

https://stackoverflow.com/questions/1068834/object-comparison-in-javascript

2021-10-28 09:27 UTC, yakkomajuri commented on src/utils/db/db.ts
> +        if (this.kafkaProducer && personFound && personFound.properties != props) {
I think `JSON.stringify` should be enough for us here btw

2021-10-28 09:27 UTC, yakkomajuri commented on src/worker/ingestion/process-event.ts
> +    private sanitizePropertiesOnce(properties: Properties, propertiesOnce: Properties): void {
nice

2021-10-28 15:45 UTC, tiina303 commented
Will move to the new merged repo

2021-10-28 15:45 UTC, closed without merging